Update java.yml

diff --git a/.github/workflows/java.yml b/.github/workflows/java.yml
--- a/.github/workflows/java.yml
+++ b/.github/workflows/java.yml
@@ -15,8 +15,8 @@ jobs:
       - name: Make Gradle wrapper executable
         run: chmod +x lab3/gradlew
 
-      - name: Validate Gradle wrapper
-        run: cd lab3 && ./gradlew wrapperValidation
+      - name: Check Gradle wrapper presence
+        run: test -f lab3/gradlew || (echo "Gradle wrapper not found!" && exit 1)
 
       - name: Set up JDK 21
         uses: actions/setup-java@v4
